name: "Test"

on:
  schedule:
    - cron: 0 6 * * *

  push:
    branches:
      - main
      - test
    paths:
      - .github/workflows/test.yml
      - .github/workflows/test-runner-image.yml

jobs:
  add_commit:
    name: Add Empty Commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      commit_hash: ${{ steps.add_commit.outputs.commit_hash }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add Empty Commit
        id: add_commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add empty commit
          commit_options: --allow-empty
          skip_dirty_check: true

  test_ubuntu_2204:
    name: "Test: ubuntu-22.04" # ubuntu-latest (2023-03-30)
    needs: add_commit
    uses: ./.github/workflows/test-runner-image.yml
    with:
      runner_image: ubuntu-22.04
      workflow_ref: ${{ github.ref }}
      exact_hash: ${{ needs.add_commit.outputs.commit_hash }}

  test_ubuntu_2004:
    name: "Test: ubuntu-20.04"
    needs: add_commit
    uses: ./.github/workflows/test-runner-image.yml
    with:
      runner_image: ubuntu-20.04
      workflow_ref: ${{ github.ref }}
      exact_hash: ${{ needs.add_commit.outputs.commit_hash }}

  test_macos_12:
    name: "Test: macos-12" # macos-latest (2023-03-30)
    needs: add_commit
    uses: ./.github/workflows/test-runner-image.yml
    with:
      runner_image: macos-12
      workflow_ref: ${{ github.ref }}
      exact_hash: ${{ needs.add_commit.outputs.commit_hash }}

  test_macos_11:
    name: "Test: macos-11"
    needs: add_commit
    uses: ./.github/workflows/test-runner-image.yml
    with:
      runner_image: macos-11
      workflow_ref: ${{ github.ref }}
      exact_hash: ${{ needs.add_commit.outputs.commit_hash }}

  test_windows_2022:
    name: "Test: windows-2022" # windows-latest (2023-03-30)
    needs: add_commit
    uses: ./.github/workflows/test-runner-image.yml
    with:
      runner_image: windows-2022
      workflow_ref: ${{ github.ref }}
      exact_hash: ${{ needs.add_commit.outputs.commit_hash }}

  test_windows_2019:
    name: "Test: windows-2019"
    needs: add_commit
    uses: ./.github/workflows/test-runner-image.yml
    with:
      runner_image: windows-2019
      workflow_ref: ${{ github.ref }}
      exact_hash: ${{ needs.add_commit.outputs.commit_hash }}

  update_test_results_data_file:
    name: Commit JSON Test Results to Data File
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - add_commit
      - test_ubuntu_2204
      - test_ubuntu_2004
      - test_macos_12
      - test_macos_11
      - test_windows_2022
      - test_windows_2019
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.add_commit.outputs.commit_hash }}

      - name: Append Test Results to data/test-results.json
        run: |
          tmp=$(mktemp)
          outfile=data/test-results.json
          jq \
            --argjson result_ubuntu_2204  '${{ needs.test_ubuntu_2204.outputs.json_test_results }}' \
            --argjson result_ubuntu_2004  '${{ needs.test_ubuntu_2004.outputs.json_test_results }}' \
            --argjson result_macos_12     '${{ needs.test_macos_12.outputs.json_test_results }}' \
            --argjson result_macos_11     '${{ needs.test_macos_11.outputs.json_test_results }}' \
            --argjson result_windows_2022 '${{ needs.test_windows_2022.outputs.json_test_results }}' \
            --argjson result_windows_2019 '${{ needs.test_windows_2019.outputs.json_test_results }}' \
            '. += [{
              "date": (now | todateiso8601),
              "results": [
                $result_ubuntu_2204,
                $result_ubuntu_2004,
                $result_macos_12,
                $result_macos_11,
                $result_windows_2022,
                $result_windows_2019
              ]
            }]' \
            "$outfile" > "$tmp" && mv "$tmp" "$outfile"

      - name: Commit data/test-results.json Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update data/test-results.json
          branch: ${{ github.ref_name }}
