on:
  workflow_call:
    inputs:
      runner_image:
        description: The GitHub Actions runner image to be tested
        required: true
        type: string

      workflow_ref:
        description: The `github.ref` value from the workflow run context
        required: true
        type: string

      exact_hash:
        description: The exact hash to checkout
        required: true
        type: string

    outputs:
      json_test_results:
        description: Test results as JSON
        value: ${{ jobs.jsonify_test_results.outputs.json }}

jobs:
  git_version:
    runs-on: ${{ inputs.runner_image }}
    outputs:
      version: ${{ steps.git_version.outputs.version }}
    steps:
      - id: git_version
        run: echo "version=$(git --version)" >> $GITHUB_OUTPUT
        shell: bash

  default_checkout:
    runs-on: ${{ inputs.runner_image }}
    outputs:
      commit_hash: ${{ steps.head_commit_hash.outputs.commit_hash }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - id: head_commit_hash
        run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        shell: bash

  default_checkout_and_pull:
    runs-on: ${{ inputs.runner_image }}
    outputs:
      commit_hash: ${{ steps.head_commit_hash.outputs.commit_hash }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - run: git pull
        shell: bash

      - id: head_commit_hash
        run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        shell: bash

  checkout_workflow_ref:
    runs-on: ${{ inputs.runner_image }}
    outputs:
      commit_hash: ${{ steps.head_commit_hash.outputs.commit_hash }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.workflow_ref }}

      - id: head_commit_hash
        run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        shell: bash

  checkout_exact:
    runs-on: ${{ inputs.runner_image }}
    outputs:
      commit_hash: ${{ steps.head_commit_hash.outputs.commit_hash }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.exact_hash }}

      - id: head_commit_hash
        run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        shell: bash

  jsonify_test_results:
    name: Jsonify Test Results
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.jsonify.outputs.json }}
    needs:
      - git_version
      - default_checkout
      - default_checkout_and_pull
      - checkout_workflow_ref
      - checkout_exact
    steps:
      - id: jsonify
        shell: bash
        run: |
          echo "json=$(jq \
            --null-input \
            --compact-output \
            \
            --arg image "${{ inputs.runner_image }}" \
            --arg gitVersion "${{ needs.git_version.outputs.version }}" \
            \
            --arg defaultCheckoutExpected "${{ github.sha }}" \
            --arg defaultCheckoutActual "${{ needs.default_checkout.outputs.commit_hash }}" \
            \
            --arg defaultCheckoutAndPullExpected "${{ inputs.exact_hash }}" \
            --arg defaultCheckoutAndPullActual "${{ needs.default_checkout_and_pull.outputs.commit_hash }}" \
            \
            --arg checkoutWorkflowRefExpected "${{ inputs.exact_hash }}" \
            --arg checkoutWorkflowRefActual "${{ needs.checkout_workflow_ref.outputs.commit_hash }}" \
            \
            --arg checkoutExact "${{ inputs.exact_hash }}" \
            --arg checkoutExactActual "${{ needs.checkout_exact.outputs.commit_hash }}" \
            '{
              "image": $image,
              "gitVersion": $gitVersion,
              "defaultCheckout": {
                "expectedHash": $defaultCheckoutExpected,
                "actualHash": $defaultCheckoutActual
              },
              "defaultCheckoutAndPull": {
                "expectedHash": $defaultCheckoutAndPullExpected,
                "actualHash": $defaultCheckoutAndPullActual
              },
              "checkoutWorkflowRef": {
                "expectedHash": $checkoutWorkflowRefExpected,
                "actualHash": $checkoutWorkflowRefActual
              },
              "checkoutExact": {
                "expectedHash": $checkoutExactExpected,
                "actualHash": $checkoutExactActual
              }
            }')" >> $GITHUB_OUTPUT

